apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: {{ .Values.gateway.namespace }}
spec:
  hosts:
    - {{ .Values.domain }}
  gateways:
    - {{ .Values.gateway.name }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.argocdPath }}
        - uri:
            prefix: {{ .Values.argocdPath }}/
      rewrite:
        uri: /
      route:
        - destination:
            host: argocd-server
            port:
              number: {{ .Values.gateway.targetPort }}