apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${CLUSTER_ISSUER_NAME}
spec:
  acme:
    email: ${EMAIL}
    server: ${CLUSTER_ISSUER_SERVER}
    privateKeySecretRef:
      name: ${CLUSTER_ISSUER_NAME}-key
    solvers:
    - http01:
        ingress:
          class: istio