name: Deploy ArgoCD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_B64}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Add Helm Repositories
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm || true
          helm repo update

      - name: Install Cert-Manager
        run: |
          ./scripts/install-cert-manager.sh

      - name: Deploy ArgoCD
        run: |
          ./scripts/install-argocd.sh

      - name: Deploy Istio Gateway and VirtualService
        un: |
          ./scripts/install-argocd.sh

      - name: Verify Deployments
        run: |
          kubectl get pods -n argocd -o wide || echo "::warning::Failed to list pods"
          kubectl get svc -n argocd || echo "::warning::Failed to list services"
          kubectl get gateway -n argocd || echo "::warning::Failed to list gateways"
          kubectl get virtualservice -n argocd || echo "::warning::Failed to list virtualservices"

      - name: Cleanup
        if: always()
        run: rm -f $HOME/.kube/config